name: Update release draft 🗒️

on:
  push:
    branches:
      - main
  # pull_request event is required only for autolabeler
  pull_request:
    types: [opened, reopened, synchronize]
  # pull_request_target event is required for autolabeler to support PRs from forks
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  compile-and-deploy-docs:
    uses: kryoniteorg/.github/.github/workflows/release-drafter.yaml@main
